on:
  push:
    branches: [main]
    
jobs:
  deploy:
    name: Deploy to DigitalOcean Droplet
    runs-on: self-hosted
    steps:
      - name: Get permissions
        run: |
          chown -R $USER:$USER /ovt-actions-runner/_work/open-virtual-tours
      - name: Download files from the current repository
        uses: actions/checkout@v2
      - name: To Droplet 
        run: |
          docker compose down
          docker compose up -d --build
